### ISSUE TITLE
Segmentation fault when Updating

### ISSUE THREAD

**Issue by Juliaaan2502** [chiyokolinux/kawa#10]
I wanted to update my packages today, but then this error came up:
![image](https://user-images.githubusercontent.com/81520713/130367771-d630177b-b9a5-43ac-b3fb-632b8530ffcc.png)

Distrobution: Debian GNU/Linux 10 Buster
Kernel: 5.10.16.3-microsoft-standard-WSL2

**Comment by em1lyy** [comment]
this looks like an error on your side.
what is your INSTALLPREFIX ?
and do you have the required files stated in the README present and populated there?
did you sync all your repos at least once before running kawa update?
please check all of these

**Comment by Juliaaan2502** [comment]
> what is your INSTALLPREFIX ?
Wut?

> and do you have the required files stated in the README present and populated there?
yes
![image](https://user-images.githubusercontent.com/81520713/130623284-80c75b74-8a2a-400c-bbe8-538d539053a7.png)

> did you sync all your repos at least once before running kawa update?
![image](https://user-images.githubusercontent.com/81520713/130623376-2c6d9212-b393-4fa6-89ba-a63439719b51.png)

**Comment by em1lyy** [comment]
> what is your INSTALLPREFIX ?
> Wut?
check your config.h before compiling (if you already have a "bad" build, you'll need to run `make clean all` instead of just `make`). INSTALLPREFIX is currently set to a testing directory on my machine; judging from your screenshot, you'll probably want to set it to "".

also, you have the community and contrib repos added. those are not yet populated and thus do not yet have a packages.db file available. please remove them from your `repos.conf` file.

i am pretty sure that that (if followed correctly) will fix any issues, thus i am closing this.
if not, contact me on discord.
